# Generated by Django 2.1.4 on 2018-12-25 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload', models.FileField(blank=True, default='No file uploaded', null=True, upload_to='assignments/')),
                ('due_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('course_code', models.CharField(max_length=8)),
                ('course_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='No description', max_length=100, null=True)),
                ('upload', models.FileField(blank=True, upload_to='submissions/')),
                ('submitted_at', models.DateField(default=None)),
                ('status', models.CharField(choices=[('To-do', 'TODO'), ('Doing', 'DOING'), ('Done', 'DONE')], max_length=20)),
                ('last_updated', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='student.Assignment')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='student',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='teacher',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
