# Generated by Django 2.1.4 on 2018-12-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20181225_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Doing', 'DOING'), ('Done', 'DONE')], max_length=20),
        ),
    ]
