# Generated by Django 2.1.4 on 2018-12-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20181225_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='teacher',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
