# Generated by Django 2.1.4 on 2018-12-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20181225_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='teacher',
            field=models.BooleanField(default=True),
        ),
    ]
