# Generated by Django 2.1.4 on 2019-01-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
