# Generated by Django 2.1.4 on 2019-01-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_submission_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='title',
            new_name='submission_title',
        ),
    ]
